### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by chenqinghe** [wuyongxiu/CodePracticeEveryDay#1]
https://github.com/wuyongxiu/CodePracticeEveryDay/blob/474bd947f76212594ad4842b77a126510b56010e/201910/d15_longest_palindrome_string.go#L28

it could be:
 longestPalindromeStrNum +=  (num/2)*2

**Comment by wuyongxiu** [comment]
丧心病狂== 为嘛瞎写写的也有人看

**Comment by wuyongxiu** [comment]
> https://github.com/wuyongxiu/CodePracticeEveryDay/blob/474bd947f76212594ad4842b77a126510b56010e/201910/d15_longest_palindrome_string.go#L28
> 
> it could be:
> longestPalindromeStrNum += (num/2)*2

已修复。不过不知道为啥单元测试运行正常==

**Comment by chenqinghe** [comment]
逻辑是没有问题的，就是那个写法有点尴尬==

**Comment by wuyongxiu** [comment]
> 逻辑是没有问题的，就是那个写法有点尴尬==

感谢指正
